spring.application.name=spring-boot-url-shortner

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password=******
spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto=update

