spring.application.name=spring-boot-url-shortner

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password=Harsha@2006

#spring.jpa.hibernate.ddl-auto=update

